import type {
  AcademicAttendanceDayRecord,
  AcademicAttendanceRecord,
  AcademicAttendanceStatRecord,
  AcademicExamRecord,
  AcademicExamResourceRecord,
  AcademicGradePointRecord,
  AcademicHomeworkAttachmentRecord,
  AcademicHomeworkRecord,
  AcademicReportCardRecord,
  AcademicScheduleEntryRecord,
  AcademicScheduleUpdateRecord,
  AcademicSubjectGradeRecord,
  ChildAcademicsRecord
} from './types.ts'

function textAsset(title: string, body: string) {
  return `data:text/plain;charset=utf-8,${encodeURIComponent(`${title}\n\n${body}`)}`
}

function imageAsset(label: string, tone: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800"><rect width="1200" height="800" fill="${tone}" rx="48"/><rect x="72" y="72" width="1056" height="656" rx="36" fill="rgba(255,255,255,0.18)"/><text x="96" y="170" fill="#ffffff" font-family="Aptos,Segoe UI,sans-serif" font-size="72" font-weight="700">${label}</text><text x="96" y="248" fill="rgba(255,255,255,0.84)" font-family="Aptos,Segoe UI,sans-serif" font-size="30">School OS academic attachment preview</text></svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

function scheduleEntry(entry: AcademicScheduleEntryRecord): AcademicScheduleEntryRecord {
  return entry
}

function scheduleUpdate(update: AcademicScheduleUpdateRecord): AcademicScheduleUpdateRecord {
  return update
}

function gradePoint(point: AcademicGradePointRecord): AcademicGradePointRecord {
  return point
}

function subjectGrade(grade: AcademicSubjectGradeRecord): AcademicSubjectGradeRecord {
  return grade
}

function reportCard(card: AcademicReportCardRecord): AcademicReportCardRecord {
  return card
}

function attachment(item: AcademicHomeworkAttachmentRecord): AcademicHomeworkAttachmentRecord {
  return item
}

function homework(item: AcademicHomeworkRecord): AcademicHomeworkRecord {
  return item
}

function resource(item: AcademicExamResourceRecord): AcademicExamResourceRecord {
  return item
}

function exam(item: AcademicExamRecord): AcademicExamRecord {
  return item
}

function attendanceStat(item: AcademicAttendanceStatRecord): AcademicAttendanceStatRecord {
  return item
}

function attendanceDay(item: AcademicAttendanceDayRecord): AcademicAttendanceDayRecord {
  return item
}

function attendance(record: AcademicAttendanceRecord): AcademicAttendanceRecord {
  return record
}

export const childAcademicsById: Record<string, ChildAcademicsRecord> = {
  'student-lina': {
    overallAverage: '15.4/20',
    classAverage: '14.8/20',
    yearComparison: '+1.3 points vs Trimester 2 of 2025',
    rankingEnabled: true,
    reportCard: reportCard({ trimesterLabel: 'Trimester 2 report card', publishedAt: 'March 5, 2026', termId: 't2' }),
    scheduleEntries: [
      scheduleEntry({ id: 'lina-mon-math', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T08:00:00+01:00', endsAt: '2026-03-16T08:50:00+01:00', subject: 'Math', teacher: 'Ms. Zohra', room: 'Room 4A', color: '#2d6a8a', notificationLeadMinutes: 15 }),
      scheduleEntry({ id: 'lina-mon-french', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T10:00:00+01:00', endsAt: '2026-03-16T10:50:00+01:00', subject: 'French', teacher: 'Mr. Karim', room: 'Room 4A', color: '#b45a44', notificationLeadMinutes: 15 }),
      scheduleEntry({ id: 'lina-mon-sports', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T14:00:00+01:00', endsAt: '2026-03-16T14:45:00+01:00', subject: 'Sports', teacher: 'Coach Salim', room: 'Gym Hall', color: '#c18d2e', notificationLeadMinutes: 20, note: 'Bring indoor trainers.' }),
      scheduleEntry({ id: 'lina-tue-science', dayId: 'tue', dayLabel: 'Tuesday', dateLabel: 'Mar 17', startsAt: '2026-03-17T08:00:00+01:00', endsAt: '2026-03-17T08:50:00+01:00', subject: 'Science', teacher: 'Ms. Nadia', room: 'Lab 1', color: '#2f8a62', notificationLeadMinutes: 15, changeLabel: 'Teacher swap confirmed for this session.' }),
      scheduleEntry({ id: 'lina-tue-english', dayId: 'tue', dayLabel: 'Tuesday', dateLabel: 'Mar 17', startsAt: '2026-03-17T11:00:00+01:00', endsAt: '2026-03-17T11:50:00+01:00', subject: 'English', teacher: 'Ms. Sofia', room: 'Room 4A', color: '#5267c8', notificationLeadMinutes: 15 }),
      scheduleEntry({ id: 'lina-wed-math', dayId: 'wed', dayLabel: 'Wednesday', dateLabel: 'Mar 18', startsAt: '2026-03-18T08:00:00+01:00', endsAt: '2026-03-18T08:50:00+01:00', subject: 'Math', teacher: 'Ms. Zohra', room: 'Lab 2', color: '#2d6a8a', notificationLeadMinutes: 15, isExamDay: true, note: 'Short fractions checkpoint.' }),
      scheduleEntry({ id: 'lina-wed-science', dayId: 'wed', dayLabel: 'Wednesday', dateLabel: 'Mar 18', startsAt: '2026-03-18T10:00:00+01:00', endsAt: '2026-03-18T10:50:00+01:00', subject: 'Science', teacher: 'Ms. Nadia', room: 'Lab 1', color: '#2f8a62', notificationLeadMinutes: 15, isExamDay: true }),
      scheduleEntry({ id: 'lina-thu-writing', dayId: 'thu', dayLabel: 'Thursday', dateLabel: 'Mar 19', startsAt: '2026-03-19T09:00:00+01:00', endsAt: '2026-03-19T09:50:00+01:00', subject: 'Writing', teacher: 'Mr. Karim', room: 'Room 4A', color: '#7b5a48', notificationLeadMinutes: 15 }),
      scheduleEntry({ id: 'lina-thu-art', dayId: 'thu', dayLabel: 'Thursday', dateLabel: 'Mar 19', startsAt: '2026-03-19T13:30:00+01:00', endsAt: '2026-03-19T14:20:00+01:00', subject: 'Art', teacher: 'Ms. Hajar', room: 'Art Studio', color: '#9e5ca8', notificationLeadMinutes: 20 }),
      scheduleEntry({ id: 'lina-fri-french', dayId: 'fri', dayLabel: 'Friday', dateLabel: 'Mar 20', startsAt: '2026-03-20T08:30:00+01:00', endsAt: '2026-03-20T09:20:00+01:00', subject: 'French', teacher: 'Mr. Karim', room: 'Room 4A', color: '#b45a44', notificationLeadMinutes: 15, isExamDay: true, note: 'Reading comprehension exam block.' }),
      scheduleEntry({ id: 'lina-fri-library', dayId: 'fri', dayLabel: 'Friday', dateLabel: 'Mar 20', startsAt: '2026-03-20T11:00:00+01:00', endsAt: '2026-03-20T11:40:00+01:00', subject: 'Library', teacher: 'Ms. Sofia', room: 'Media Corner', color: '#6a7b89', notificationLeadMinutes: 15 })
    ],
    scheduleUpdates: [
      scheduleUpdate({ id: 'lina-update-room', tone: 'warning', title: 'Math room swap', detail: 'Wednesday 08:00 Math moved from Room 4A to Lab 2. A parent notification was queued immediately.', effectiveAt: 'Mar 18, 07:42' }),
      scheduleUpdate({ id: 'lina-update-teacher', tone: 'info', title: 'Science teacher cover', detail: 'Tuesday Science will be led by Ms. Nadia while the regular teacher is at training.', effectiveAt: 'Mar 17, 06:55' })
    ],
    gradePoints: [
      gradePoint({ label: 'Sep', score: 13.8, classAverage: 13.2 }),
      gradePoint({ label: 'Nov', score: 14.4, classAverage: 13.7 }),
      gradePoint({ label: 'Jan', score: 14.9, classAverage: 14.2 }),
      gradePoint({ label: 'Feb', score: 15.1, classAverage: 14.6 }),
      gradePoint({ label: 'Mar', score: 15.4, classAverage: 14.8 })
    ],
    subjectGrades: [
      subjectGrade({ id: 'lina-grade-math', subject: 'Math', color: '#2d6a8a', latestGrade: '16.4/20', classAverage: '15.1/20', teacherComment: 'Lina is solving multi-step fraction problems with more confidence and checking her work carefully.', ranking: 'Top 5 in class', breakdown: ['Fractions quiz: 17/20', 'Mental math: 16/20', 'Homework completion: 100%'], trimesterDelta: '+0.8 since last progress check', yearOverYear: '+1.5 vs last year' }),
      subjectGrade({ id: 'lina-grade-french', subject: 'French', color: '#b45a44', latestGrade: '15.2/20', classAverage: '14.5/20', teacherComment: 'Her written expression is clearer, and reading fluency remains above target for Grade 4.', ranking: 'Top 8 in class', breakdown: ['Grammar assessment: 15/20', 'Reading journal: 16/20', 'Oral participation: Excellent'], trimesterDelta: '+0.4 this trimester', yearOverYear: '+1.1 vs last year' }),
      subjectGrade({ id: 'lina-grade-science', subject: 'Science', color: '#2f8a62', latestGrade: '15.8/20', classAverage: '14.2/20', teacherComment: 'Strong curiosity in experiments and careful lab observations.', ranking: 'Top 6 in class', breakdown: ['Experiment logbook: 16/20', 'Vocabulary quiz: 15/20', 'Project prototype: 16.5/20'], trimesterDelta: '+0.9 since January', yearOverYear: '+1.7 vs last year' }),
      subjectGrade({ id: 'lina-grade-english', subject: 'English', color: '#5267c8', latestGrade: '14.3/20', classAverage: '14.0/20', teacherComment: 'Listening comprehension is steady, with room to push vocabulary precision.', ranking: 'Top 10 in class', breakdown: ['Reading response: 14/20', 'Spelling check: 15/20', 'Presentation: 14/20'], trimesterDelta: '+0.2 since last month', yearOverYear: '+0.9 vs last year' })
    ],
    homework: [
      homework({ id: 'lina-hw-math', subject: 'Math', color: '#2d6a8a', title: 'Fractions worksheet and revision quiz', dueAt: '2026-03-17T18:00:00+01:00', status: 'pending', attachments: [attachment({ label: 'Worksheet PDF', kind: 'pdf', url: textAsset('Fractions worksheet', 'Practice simplifying and comparing fractions before Tuesday evening.') }), attachment({ label: 'Worked examples', kind: 'image', url: imageAsset('Fractions examples', '#2d6a8a') })], feedback: null, parentNotification: 'Reminder scheduled if the worksheet is still pending by 17:00.', submittedAt: null }),
      homework({ id: 'lina-hw-science', subject: 'Science', color: '#2f8a62', title: 'Science fair poster draft', dueAt: '2026-03-19T17:30:00+01:00', status: 'submitted', attachments: [attachment({ label: 'Poster brief', kind: 'pdf', url: textAsset('Science fair poster brief', 'Draft the poster introduction, hypothesis, and materials list.') }), attachment({ label: 'Reference article', kind: 'link', url: 'https://example.com/science-fair-guidelines' })], feedback: 'Teacher feedback: clear hypothesis and great visual structure. Add one more sentence about variables.', parentNotification: null, submittedAt: '2026-03-18T16:15:00+01:00' }),
      homework({ id: 'lina-hw-french', subject: 'French', color: '#b45a44', title: 'Reading log reflection', dueAt: '2026-03-14T20:00:00+01:00', status: 'late', attachments: [attachment({ label: 'Reading log template', kind: 'pdf', url: textAsset('Reading log template', 'Write three short reflection sentences about this week\'s story.') })], feedback: 'Teacher feedback: still accepted, but submitted after the family deadline window.', parentNotification: 'Late submission alert was sent to the parent account on March 14 at 20:15.', submittedAt: '2026-03-15T08:45:00+01:00' })
    ],
    exams: [
      exam({ id: 'lina-exam-science', subject: 'Science practical', color: '#2f8a62', startsAt: '2026-03-18T10:00:00+01:00', endsAt: '2026-03-18T10:50:00+01:00', room: 'Lab 1', syllabus: ['Plant life cycles', 'Observation vocabulary', 'Simple experiment safety'], result: null, reminderDate: 'March 16, 2026', resources: [resource({ label: 'Practical revision sheet', url: textAsset('Science practical revision', 'Review plant life cycles, diagrams, and observation vocabulary.') })], retake: null }),
      exam({ id: 'lina-exam-french', subject: 'French comprehension', color: '#b45a44', startsAt: '2026-03-20T08:30:00+01:00', endsAt: '2026-03-20T09:20:00+01:00', room: 'Room 4A', syllabus: ['Inference questions', 'Vocabulary in context', 'Paragraph sequencing'], result: null, reminderDate: 'March 18, 2026', resources: [resource({ label: 'Practice passage', url: textAsset('French comprehension practice', 'Read the passage and answer the five inference questions.') })], retake: null }),
      exam({ id: 'lina-exam-math-past', subject: 'Math checkpoint', color: '#2d6a8a', startsAt: '2026-03-04T09:00:00+01:00', endsAt: '2026-03-04T09:45:00+01:00', room: 'Room 4A', syllabus: ['Fractions', 'Equivalent values', 'Word problems'], result: '17/20 published March 6', reminderDate: 'March 2, 2026', resources: [resource({ label: 'Correction notes', url: textAsset('Math checkpoint corrections', 'Review the method for simplifying fractions and showing your working.') })], retake: null })
    ],
    attendance: attendance({ todayStatus: 'present', todayDetail: 'Checked in at 07:53 and marked present for all academic blocks.', notification: 'Instant attendance notifications are active for absence and tardiness changes.', stats: [attendanceStat({ label: 'This month', value: '96%', detail: '1 absence and 1 late arrival in March' }), attendanceStat({ label: 'Year to date', value: '97.4%', detail: 'Above the school attendance target' }), attendanceStat({ label: 'Justified absences', value: '2', detail: 'All reasons approved by the school office' }), attendanceStat({ label: 'Unjustified absences', value: '0', detail: 'No unresolved absence cases' })], history: [attendanceDay({ id: 'lina-att-0312', dateLabel: 'Mar 12', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'lina-att-0311', dateLabel: 'Mar 11', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'lina-att-0310', dateLabel: 'Mar 10', status: 'late', reason: 'Traffic delay', justified: true, note: 'Arrived 9 minutes late' }), attendanceDay({ id: 'lina-att-0309', dateLabel: 'Mar 9', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'lina-att-0305', dateLabel: 'Mar 5', status: 'absent', reason: 'Medical appointment', justified: true, note: 'Reason received in app and approved' })], impact: 'Attendance tracking is enabled for academics, but there is currently no negative impact on grades or behavior for Lina.', absenceGuidance: 'If Lina is absent again, a parent note submitted before 08:30 will immediately mark the case as awaiting school approval.' })
  },
  'student-yanis': {
    overallAverage: '14.7/20',
    classAverage: '14.3/20',
    yearComparison: 'First-year baseline is trending positively across reading and art.',
    rankingEnabled: false,
    reportCard: reportCard({ trimesterLabel: 'Trimester 2 progress report', publishedAt: 'March 4, 2026', termId: 't2' }),
    scheduleEntries: [scheduleEntry({ id: 'yanis-mon-reading', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T08:30:00+01:00', endsAt: '2026-03-16T09:10:00+01:00', subject: 'Reading', teacher: 'Ms. Imane', room: 'Olive Class', color: '#7c5a3d', notificationLeadMinutes: 20 }), scheduleEntry({ id: 'yanis-mon-art', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T10:15:00+01:00', endsAt: '2026-03-16T10:55:00+01:00', subject: 'Art', teacher: 'Ms. Hajar', room: 'Art Corner', color: '#9e5ca8', notificationLeadMinutes: 20 }), scheduleEntry({ id: 'yanis-mon-move', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T13:30:00+01:00', endsAt: '2026-03-16T14:05:00+01:00', subject: 'Play & Movement', teacher: 'Coach Salim', room: 'Early Years Hall', color: '#c18d2e', notificationLeadMinutes: 20 }), scheduleEntry({ id: 'yanis-tue-phonics', dayId: 'tue', dayLabel: 'Tuesday', dateLabel: 'Mar 17', startsAt: '2026-03-17T08:30:00+01:00', endsAt: '2026-03-17T09:10:00+01:00', subject: 'Phonics', teacher: 'Ms. Imane', room: 'Olive Class', color: '#5267c8', notificationLeadMinutes: 20 }), scheduleEntry({ id: 'yanis-wed-reading', dayId: 'wed', dayLabel: 'Wednesday', dateLabel: 'Mar 18', startsAt: '2026-03-18T08:30:00+01:00', endsAt: '2026-03-18T09:10:00+01:00', subject: 'Reading', teacher: 'Ms. Imane', room: 'Olive Class', color: '#7c5a3d', notificationLeadMinutes: 20, isExamDay: true, note: 'Short guided reading check.' }), scheduleEntry({ id: 'yanis-thu-art', dayId: 'thu', dayLabel: 'Thursday', dateLabel: 'Mar 19', startsAt: '2026-03-19T10:15:00+01:00', endsAt: '2026-03-19T10:55:00+01:00', subject: 'Art', teacher: 'Ms. Hajar', room: 'Art Corner', color: '#9e5ca8', notificationLeadMinutes: 20 }), scheduleEntry({ id: 'yanis-fri-story', dayId: 'fri', dayLabel: 'Friday', dateLabel: 'Mar 20', startsAt: '2026-03-20T09:00:00+01:00', endsAt: '2026-03-20T09:35:00+01:00', subject: 'Story Circle', teacher: 'Ms. Imane', room: 'Library Nook', color: '#5d7a8d', notificationLeadMinutes: 20 })],
    scheduleUpdates: [scheduleUpdate({ id: 'yanis-update-art', tone: 'info', title: 'Art materials reminder', detail: 'Thursday art session requires a small apron and tissue pack. The class reminder will go out 20 minutes before pickup.', effectiveAt: 'Mar 19, 07:10' })],
    gradePoints: [gradePoint({ label: 'Sep', score: 13.1, classAverage: 13.0 }), gradePoint({ label: 'Nov', score: 13.8, classAverage: 13.5 }), gradePoint({ label: 'Jan', score: 14.1, classAverage: 13.8 }), gradePoint({ label: 'Feb', score: 14.5, classAverage: 14.0 }), gradePoint({ label: 'Mar', score: 14.7, classAverage: 14.3 })],
    subjectGrades: [subjectGrade({ id: 'yanis-grade-reading', subject: 'Reading', color: '#7c5a3d', latestGrade: '15.1/20', classAverage: '14.4/20', teacherComment: 'Yanis is recognising more sight words independently and enjoys reading aloud.', ranking: null, breakdown: ['Guided reading: 15/20', 'Reading log: Consistent', 'Phonics quiz: 15/20'], trimesterDelta: '+0.7 this trimester', yearOverYear: 'First-year baseline set' }), subjectGrade({ id: 'yanis-grade-art', subject: 'Art', color: '#9e5ca8', latestGrade: '14.8/20', classAverage: '14.6/20', teacherComment: 'He follows creative instructions well and is becoming more precise with shapes and color choices.', ranking: null, breakdown: ['Painting task: 15/20', 'Cut-and-paste craft: 14/20', 'Participation: Excellent'], trimesterDelta: '+0.4 since January', yearOverYear: 'First-year baseline set' }), subjectGrade({ id: 'yanis-grade-phonics', subject: 'Phonics', color: '#5267c8', latestGrade: '14.2/20', classAverage: '13.9/20', teacherComment: 'Strong sound recognition, with a little more time needed on blending unfamiliar words.', ranking: null, breakdown: ['Letter sounds: 14/20', 'Blend practice: 14/20', 'Listening game: Great'], trimesterDelta: '+0.5 this trimester', yearOverYear: 'First-year baseline set' })],
    homework: [homework({ id: 'yanis-hw-reading', subject: 'Reading', color: '#7c5a3d', title: 'Nightly reading folder', dueAt: '2026-03-16T19:00:00+01:00', status: 'pending', attachments: [attachment({ label: 'Story text', kind: 'pdf', url: textAsset('Reading folder', 'Please read tonight\'s short story together and sign the reading log.') })], feedback: null, parentNotification: 'A family reminder will be sent if the reading log is not marked complete before bedtime.', submittedAt: null }), homework({ id: 'yanis-hw-art', subject: 'Art', color: '#9e5ca8', title: 'Bring a family photo for collage', dueAt: '2026-03-18T08:00:00+01:00', status: 'submitted', attachments: [attachment({ label: 'Collage example', kind: 'image', url: imageAsset('Family collage', '#9e5ca8') })], feedback: 'Teacher feedback: photo received and ready for Thursday\'s project.', parentNotification: null, submittedAt: '2026-03-17T20:05:00+01:00' })],
    exams: [exam({ id: 'yanis-exam-reading', subject: 'Guided reading check', color: '#7c5a3d', startsAt: '2026-03-18T08:30:00+01:00', endsAt: '2026-03-18T09:10:00+01:00', room: 'Olive Class', syllabus: ['Letter sounds', 'High-frequency words', 'Simple sentence fluency'], result: null, reminderDate: 'March 16, 2026', resources: [resource({ label: 'Sight word cards', url: textAsset('Sight word cards', 'Review the highlighted words in the family reading folder.') })], retake: null })],
    attendance: attendance({ todayStatus: 'present', todayDetail: 'Present today with a smooth morning check-in.', notification: 'Parents receive an instant message if Yanis is absent or arrives late.', stats: [attendanceStat({ label: 'This month', value: '98%', detail: 'One approved absence in March' }), attendanceStat({ label: 'Year to date', value: '98.6%', detail: 'Strong attendance consistency' }), attendanceStat({ label: 'Justified absences', value: '1', detail: 'Family medical visit approved' }), attendanceStat({ label: 'Unjustified absences', value: '0', detail: 'No unresolved attendance concerns' })], history: [attendanceDay({ id: 'yanis-att-0312', dateLabel: 'Mar 12', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'yanis-att-0311', dateLabel: 'Mar 11', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'yanis-att-0310', dateLabel: 'Mar 10', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'yanis-att-0306', dateLabel: 'Mar 6', status: 'absent', reason: 'Pediatric appointment', justified: true, note: 'Reason submitted in app and accepted' })], impact: 'Attendance has no grade or behavior impact configured for early years learners at the moment.', absenceGuidance: 'Use the in-app absence note before 08:15 to help the teacher plan classroom support for the day.' })
  },
  'student-adam': {
    overallAverage: '13.9/20',
    classAverage: '13.5/20',
    yearComparison: 'New campus transition is on track with steady term-over-term improvement.',
    rankingEnabled: false,
    reportCard: reportCard({ trimesterLabel: 'Atlas campus transition report', publishedAt: 'March 6, 2026', termId: 't2' }),
    scheduleEntries: [scheduleEntry({ id: 'adam-mon-english', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T09:00:00+01:00', endsAt: '2026-03-16T09:50:00+01:00', subject: 'English', teacher: 'Ms. Leila', room: 'Maple Class', color: '#5267c8', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'adam-mon-science', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T11:00:00+01:00', endsAt: '2026-03-16T11:50:00+01:00', subject: 'Science', teacher: 'Mr. Omar', room: 'Lab A', color: '#2f8a62', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'adam-mon-music', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T15:00:00+01:00', endsAt: '2026-03-16T15:40:00+01:00', subject: 'Music', teacher: 'Ms. Rania', room: 'Music Studio', color: '#8f684f', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'adam-tue-math', dayId: 'tue', dayLabel: 'Tuesday', dateLabel: 'Mar 17', startsAt: '2026-03-17T08:30:00+01:00', endsAt: '2026-03-17T09:20:00+01:00', subject: 'Math', teacher: 'Mr. Samy', room: 'Maple Class', color: '#2d6a8a', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'adam-wed-science', dayId: 'wed', dayLabel: 'Wednesday', dateLabel: 'Mar 18', startsAt: '2026-03-18T11:00:00+01:00', endsAt: '2026-03-18T11:50:00+01:00', subject: 'Science', teacher: 'Mr. Omar', room: 'Lab B', color: '#2f8a62', notificationLeadMinutes: 15, isExamDay: true, changeLabel: 'Room updated to Lab B for practical setup.' }), scheduleEntry({ id: 'adam-thu-english', dayId: 'thu', dayLabel: 'Thursday', dateLabel: 'Mar 19', startsAt: '2026-03-19T09:00:00+01:00', endsAt: '2026-03-19T09:50:00+01:00', subject: 'English', teacher: 'Ms. Leila', room: 'Maple Class', color: '#5267c8', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'adam-fri-music', dayId: 'fri', dayLabel: 'Friday', dateLabel: 'Mar 20', startsAt: '2026-03-20T15:00:00+01:00', endsAt: '2026-03-20T15:40:00+01:00', subject: 'Music', teacher: 'Ms. Rania', room: 'Music Studio', color: '#8f684f', notificationLeadMinutes: 15 })],
    scheduleUpdates: [scheduleUpdate({ id: 'adam-update-room', tone: 'warning', title: 'Science lab change', detail: 'The Wednesday science practical moved from Lab A to Lab B. Parents were notified instantly to avoid confusion at pickup.', effectiveAt: 'Mar 18, 08:05' })],
    gradePoints: [gradePoint({ label: 'Sep', score: 12.9, classAverage: 12.8 }), gradePoint({ label: 'Nov', score: 13.1, classAverage: 13.0 }), gradePoint({ label: 'Jan', score: 13.4, classAverage: 13.2 }), gradePoint({ label: 'Feb', score: 13.7, classAverage: 13.4 }), gradePoint({ label: 'Mar', score: 13.9, classAverage: 13.5 })],
    subjectGrades: [subjectGrade({ id: 'adam-grade-english', subject: 'English', color: '#5267c8', latestGrade: '14.2/20', classAverage: '13.8/20', teacherComment: 'Adam is settling into the new campus and participates more confidently in speaking activities.', ranking: null, breakdown: ['Reading response: 14/20', 'Vocabulary: 14/20', 'Participation: Strong'], trimesterDelta: '+0.6 this trimester', yearOverYear: '+0.8 vs previous campus report' }), subjectGrade({ id: 'adam-grade-science', subject: 'Science', color: '#2f8a62', latestGrade: '13.8/20', classAverage: '13.2/20', teacherComment: 'He is handling practical work well and asks thoughtful questions during experiments.', ranking: null, breakdown: ['Lab notebook: 14/20', 'Observation quiz: 13/20', 'Teamwork: Very good'], trimesterDelta: '+0.7 since January', yearOverYear: '+0.9 vs previous campus report' }), subjectGrade({ id: 'adam-grade-music', subject: 'Music', color: '#8f684f', latestGrade: '13.5/20', classAverage: '13.4/20', teacherComment: 'Comfort is growing in rhythm exercises and group performance routines.', ranking: null, breakdown: ['Rhythm task: 13/20', 'Singing practice: 14/20', 'Instrument care: Consistent'], trimesterDelta: '+0.3 this month', yearOverYear: '+0.6 vs previous campus report' })],
    homework: [homework({ id: 'adam-hw-english', subject: 'English', color: '#5267c8', title: 'Vocabulary flashcards', dueAt: '2026-03-17T19:00:00+01:00', status: 'submitted', attachments: [attachment({ label: 'Flashcard list', kind: 'pdf', url: textAsset('Vocabulary flashcards', 'Cut out the words and review them for ten minutes each evening.') })], feedback: 'Teacher feedback: submitted on time and reviewed in class.', parentNotification: null, submittedAt: '2026-03-17T17:40:00+01:00' }), homework({ id: 'adam-hw-science', subject: 'Science', color: '#2f8a62', title: 'Plant observation journal', dueAt: '2026-03-20T18:00:00+01:00', status: 'pending', attachments: [attachment({ label: 'Journal template', kind: 'pdf', url: textAsset('Plant observation journal', 'Record one plant change each day with a drawing or short sentence.') })], feedback: null, parentNotification: 'Pending-work reminder will be sent on Friday at 16:00 if the journal is not marked complete.', submittedAt: null })],
    exams: [exam({ id: 'adam-exam-science', subject: 'Science practical', color: '#2f8a62', startsAt: '2026-03-18T11:00:00+01:00', endsAt: '2026-03-18T11:50:00+01:00', room: 'Lab B', syllabus: ['Plant parts', 'Simple observations', 'Using a results table'], result: null, reminderDate: 'March 16, 2026', resources: [resource({ label: 'Practical checklist', url: textAsset('Science practical checklist', 'Review plant parts, observation verbs, and table headings.') })], retake: null }), exam({ id: 'adam-exam-listening', subject: 'English listening quiz', color: '#5267c8', startsAt: '2026-03-06T09:00:00+01:00', endsAt: '2026-03-06T09:30:00+01:00', room: 'Maple Class', syllabus: ['Classroom vocabulary', 'Short spoken instructions'], result: '11/20 published March 8', reminderDate: 'March 4, 2026', resources: [resource({ label: 'Listening practice clip', url: textAsset('Listening practice', 'Review the short classroom instruction script with Adam.') })], retake: 'Retake scheduled for March 23 at 09:00 in Maple Class' })],
    attendance: attendance({ todayStatus: 'late', todayDetail: 'Marked late at 08:43 after the campus gate check. Parent alert was sent instantly.', notification: 'Late arrivals trigger an immediate attendance notification and appear in the full history.', stats: [attendanceStat({ label: 'This month', value: '95%', detail: 'One late arrival and one justified absence' }), attendanceStat({ label: 'Year to date', value: '95.8%', detail: 'Healthy attendance during campus transition' }), attendanceStat({ label: 'Justified absences', value: '2', detail: 'Family reasons documented and approved' }), attendanceStat({ label: 'Unjustified absences', value: '1', detail: 'One unresolved half-day absence' })], history: [attendanceDay({ id: 'adam-att-0312', dateLabel: 'Mar 12', status: 'late', reason: 'Traffic at new campus gate', justified: true, note: 'Arrived 13 minutes late' }), attendanceDay({ id: 'adam-att-0311', dateLabel: 'Mar 11', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'adam-att-0310', dateLabel: 'Mar 10', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'adam-att-0307', dateLabel: 'Mar 7', status: 'absent', reason: 'Family travel', justified: true, note: 'Reason submitted in app' }), attendanceDay({ id: 'adam-att-0303', dateLabel: 'Mar 3', status: 'absent', reason: null, justified: false, note: 'School still waiting for supporting note' })], impact: 'Atlas campus has attendance impact tracking enabled. The current pattern has only a light advisory note and no behavior deduction yet.', absenceGuidance: 'If Adam misses another day, submit a reason and any supporting note directly in the app so the absence can be reviewed before teacher follow-up.' })
  },
  'student-salma': {
    overallAverage: '17.2/20',
    classAverage: '15.9/20',
    yearComparison: '+1.0 point vs the same trimester last year',
    rankingEnabled: true,
    reportCard: reportCard({ trimesterLabel: 'Trimester 2 excellence report', publishedAt: 'March 3, 2026', termId: 't2' }),
    scheduleEntries: [scheduleEntry({ id: 'salma-mon-science', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T08:00:00+01:00', endsAt: '2026-03-16T08:55:00+01:00', subject: 'Science', teacher: 'Dr. Amal', room: 'Atlas Class', color: '#2f8a62', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'salma-mon-french', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T10:00:00+01:00', endsAt: '2026-03-16T10:55:00+01:00', subject: 'French', teacher: 'Mr. Karim', room: 'Atlas Class', color: '#b45a44', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'salma-mon-debate', dayId: 'mon', dayLabel: 'Monday', dateLabel: 'Mar 16', startsAt: '2026-03-16T14:00:00+01:00', endsAt: '2026-03-16T15:10:00+01:00', subject: 'Debate Club', teacher: 'Ms. Sara', room: 'Auditorium', color: '#9c566e', notificationLeadMinutes: 20, note: 'Final rehearsal week.' }), scheduleEntry({ id: 'salma-tue-math', dayId: 'tue', dayLabel: 'Tuesday', dateLabel: 'Mar 17', startsAt: '2026-03-17T08:00:00+01:00', endsAt: '2026-03-17T08:55:00+01:00', subject: 'Math', teacher: 'Mr. Samy', room: 'Atlas Class', color: '#2d6a8a', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'salma-wed-science', dayId: 'wed', dayLabel: 'Wednesday', dateLabel: 'Mar 18', startsAt: '2026-03-18T08:00:00+01:00', endsAt: '2026-03-18T08:55:00+01:00', subject: 'Science', teacher: 'Dr. Amal', room: 'Lab 3', color: '#2f8a62', notificationLeadMinutes: 15, isExamDay: true, note: 'Lab report assessment.' }), scheduleEntry({ id: 'salma-thu-french', dayId: 'thu', dayLabel: 'Thursday', dateLabel: 'Mar 19', startsAt: '2026-03-19T10:00:00+01:00', endsAt: '2026-03-19T10:55:00+01:00', subject: 'French', teacher: 'Mr. Karim', room: 'Atlas Class', color: '#b45a44', notificationLeadMinutes: 15 }), scheduleEntry({ id: 'salma-fri-debate', dayId: 'fri', dayLabel: 'Friday', dateLabel: 'Mar 20', startsAt: '2026-03-20T14:00:00+01:00', endsAt: '2026-03-20T15:10:00+01:00', subject: 'Debate Club', teacher: 'Ms. Sara', room: 'Auditorium', color: '#9c566e', notificationLeadMinutes: 20, isExamDay: true, note: 'Final debate performance.' })],
    scheduleUpdates: [scheduleUpdate({ id: 'salma-update-debate', tone: 'info', title: 'Debate rehearsal timing extended', detail: 'Monday debate rehearsal runs 20 minutes longer this week. Pickup timing has been updated in the parent notification feed.', effectiveAt: 'Mar 16, 09:05' })],
    gradePoints: [gradePoint({ label: 'Sep', score: 16.0, classAverage: 15.0 }), gradePoint({ label: 'Nov', score: 16.4, classAverage: 15.3 }), gradePoint({ label: 'Jan', score: 16.8, classAverage: 15.5 }), gradePoint({ label: 'Feb', score: 17.0, classAverage: 15.7 }), gradePoint({ label: 'Mar', score: 17.2, classAverage: 15.9 })],
    subjectGrades: [subjectGrade({ id: 'salma-grade-science', subject: 'Science', color: '#2f8a62', latestGrade: '17.8/20', classAverage: '16.0/20', teacherComment: 'Excellent precision in lab work and consistently strong analytical writing.', ranking: '#1 in cohort', breakdown: ['Lab report: 18/20', 'Quiz average: 17/20', 'Project work: Outstanding'], trimesterDelta: '+0.6 this trimester', yearOverYear: '+1.2 vs last year' }), subjectGrade({ id: 'salma-grade-french', subject: 'French', color: '#b45a44', latestGrade: '17.0/20', classAverage: '15.6/20', teacherComment: 'Sophisticated vocabulary and clear structure in both oral and written responses.', ranking: '#2 in cohort', breakdown: ['Essay: 17/20', 'Reading analysis: 17/20', 'Participation: Excellent'], trimesterDelta: '+0.4 this trimester', yearOverYear: '+0.9 vs last year' }), subjectGrade({ id: 'salma-grade-debate', subject: 'Debate Club', color: '#9c566e', latestGrade: '18.1/20', classAverage: '16.2/20', teacherComment: 'Salma leads with calm confidence and strong evidence-based argumentation.', ranking: '#1 in cohort', breakdown: ['Practice round: 18/20', 'Research brief: 18/20', 'Team contribution: Exceptional'], trimesterDelta: '+0.7 since January', yearOverYear: '+1.5 vs last year' })],
    homework: [homework({ id: 'salma-hw-science', subject: 'Science', color: '#2f8a62', title: 'Lab report reflection', dueAt: '2026-03-18T19:30:00+01:00', status: 'submitted', attachments: [attachment({ label: 'Reflection template', kind: 'pdf', url: textAsset('Lab report reflection', 'Summarize the investigation method, findings, and one improvement for next time.') })], feedback: 'Teacher feedback: excellent structure and very clear evaluation of the experimental method.', parentNotification: null, submittedAt: '2026-03-18T17:12:00+01:00' }), homework({ id: 'salma-hw-debate', subject: 'Debate Club', color: '#9c566e', title: 'Final rebuttal card set', dueAt: '2026-03-20T12:00:00+01:00', status: 'pending', attachments: [attachment({ label: 'Debate brief', kind: 'pdf', url: textAsset('Debate final brief', 'Prepare rebuttal cards with claims, evidence, and one closing statement.') }), attachment({ label: 'Coach notes', kind: 'link', url: 'https://example.com/debate-notes' })], feedback: null, parentNotification: 'A parent reminder will be issued two hours before the final rebuttal card deadline if still pending.', submittedAt: null })],
    exams: [exam({ id: 'salma-exam-science', subject: 'Science lab assessment', color: '#2f8a62', startsAt: '2026-03-18T08:00:00+01:00', endsAt: '2026-03-18T08:55:00+01:00', room: 'Lab 3', syllabus: ['Variables and controls', 'Lab safety', 'Evidence-based conclusions'], result: null, reminderDate: 'March 16, 2026', resources: [resource({ label: 'Lab method checklist', url: textAsset('Lab method checklist', 'Review variables, controls, and conclusion writing before the assessment.') })], retake: null }), exam({ id: 'salma-exam-debate', subject: 'Debate final performance', color: '#9c566e', startsAt: '2026-03-20T14:00:00+01:00', endsAt: '2026-03-20T15:10:00+01:00', room: 'Auditorium', syllabus: ['Opening statement', 'Cross-examination', 'Closing summary'], result: null, reminderDate: 'March 18, 2026', resources: [resource({ label: 'Coach preparation notes', url: textAsset('Debate coach notes', 'Refine your opening, anticipate counterarguments, and slow the pace in closing.') })], retake: null })],
    attendance: attendance({ todayStatus: 'present', todayDetail: 'Present and on time for the full academic day.', notification: 'Attendance alerts remain enabled, even though Salma currently has a perfect monthly record.', stats: [attendanceStat({ label: 'This month', value: '100%', detail: 'No absences or late arrivals in March' }), attendanceStat({ label: 'Year to date', value: '99.3%', detail: 'Excellent consistency' }), attendanceStat({ label: 'Justified absences', value: '1', detail: 'Single approved medical absence this year' }), attendanceStat({ label: 'Unjustified absences', value: '0', detail: 'No unresolved attendance issues' })], history: [attendanceDay({ id: 'salma-att-0312', dateLabel: 'Mar 12', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'salma-att-0311', dateLabel: 'Mar 11', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'salma-att-0310', dateLabel: 'Mar 10', status: 'present', reason: null, justified: true, note: 'On time' }), attendanceDay({ id: 'salma-att-0309', dateLabel: 'Mar 9', status: 'present', reason: null, justified: true, note: 'On time' })], impact: 'Attendance impact tracking is enabled, but Salma currently has no attendance-related academic or behavior flags.', absenceGuidance: 'If a future absence is expected, submitting the reason before the first period will automatically notify the class team and school office.' })
  }
}

