export const LANGUAGE_STORAGE_KEY = 'school-os.language'

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English', dir: 'ltr' },
  { code: 'fr', label: 'French', nativeLabel: 'Francais', dir: 'ltr' },
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية', dir: 'rtl' }
] as const

export type SupportedLanguage = (typeof SUPPORTED_LANGUAGES)[number]['code']

const messages = {
  en: {
    auth: {
      chip: 'Premium private school OS',
      title: 'One secure platform, six roles, one calm school experience.',
      body: 'Sign in with the account issued by the school or platform to enter the right workspace for parents, school teams, transport, supervision, and SaaS operations.',
      roleList: 'Roles already modeled',
      codeTab: 'School login',
      accessCodeTab: 'Unique code',
      qrTab: 'QR onboarding',
      schoolCode: 'School code',
      email: 'Email',
      password: 'Password',
      accessCode: 'Unique parent code',
      continue: 'Continue',
      biometric: 'Use biometric login',
      forgotPassword: 'Forgot password',
      recoveryTitle: 'Recover access via secure channel',
      recoveryBody: 'Send a reset path through the verified mobile channels on the account.',
      sms: 'Recover by SMS',
      whatsapp: 'Recover by WhatsApp',
      language: 'Language',
      demoTitle: 'Seed accounts for role testing',
      demoBody: 'Pick any role below to prefill the login form instantly.',
      qrTitle: 'School onboarding QR invites',
      qrBody: 'Schools can generate a secure QR invite. Scanning it opens a guided parent join flow.',
      join: 'Open QR invite',
      signInTitle: 'Secure role sign in',
      signInBody: 'Use the correct school code, email, and password to enter your assigned workspace.',
      accessCodeBody: 'Use the one-time code shared by the school to activate or enter your account.',
      biometricBody: 'Biometric sign-in is ready on this trusted device.',
      loginHint: 'Each account is routed automatically to the correct workspace after login.',
      accessHint: 'Unique codes are useful for first activation or simplified parent login.',
      qrHint: 'Scanning a QR invite takes the parent directly into a secure onboarding flow.'
    },
    onboarding: {
      title: 'Welcome to your first secure session',
      subtitle: 'A quick walkthrough sets up language, visibility, and trusted access for future visits.',
      next: 'Next',
      back: 'Back',
      finish: 'Finish setup',
      skip: 'Skip for now',
      step: 'Step',
      slides: [
        {
          title: 'Everything important appears first',
          body: 'Children, fees, updates, complaints, and operational signals are surfaced without hunting through menus.'
        },
        {
          title: 'Your language follows your preference',
          body: 'Arabic, French, and English stay available from the first login so families and staff feel comfortable immediately.'
        },
        {
          title: 'Trusted devices make return visits faster',
          body: 'Biometric login, inactivity protection, and device visibility keep access quick while staying controlled.'
        }
      ]
    },
    join: {
      title: 'Secure school invitation',
      subtitle: 'This QR invite was generated by the school for a parent account setup.',
      linkedChildren: 'Linked children',
      linkedSchools: 'Linked schools',
      continue: 'Continue with invite',
      back: 'Back to sign in',
      invalid: 'This invitation could not be found. Please ask the school for a fresh QR code.'
    },
    common: {
      signOut: 'Sign out',
      support: 'Support',
      parentDashboard: 'Parent dashboard',
      roleWorkspace: 'workspace',
      currentDevice: 'Current device',
      lastActive: 'Last active',
      trusted: 'Trusted',
      revoke: 'Remove device',
      devicesTitle: 'Logged-in devices',
      devicesBody: 'Review trusted sessions connected to this account.',
      inactivityNote: 'Auto-logout after 15 minutes of inactivity',
      roleFoundation: 'Role foundation',
      operationalSignals: 'Operational signals',
      priorities: 'Next priorities'
    }
  },
  fr: {
    auth: {
      chip: 'OS scolaire premium',
      title: 'Une plateforme securisee, six roles, une experience scolaire apaisante.',
      body: "Connectez-vous avec le compte fourni par l'ecole ou la plateforme pour ouvrir l'espace adapte aux parents, a l'administration, au transport, a la surveillance et aux operations SaaS.",
      roleList: 'Roles deja modelises',
      codeTab: 'Connexion ecole',
      accessCodeTab: 'Code unique',
      qrTab: 'QR onboarding',
      schoolCode: 'Code ecole',
      email: 'Email',
      password: 'Mot de passe',
      accessCode: 'Code parent unique',
      continue: 'Continuer',
      biometric: 'Utiliser la biometrie',
      forgotPassword: 'Mot de passe oublie',
      recoveryTitle: "Recuperer l'acces par canal securise",
      recoveryBody: 'Envoyer un parcours de reinitialisation sur les canaux mobiles verifies du compte.',
      sms: 'Recuperer par SMS',
      whatsapp: 'Recuperer par WhatsApp',
      language: 'Langue',
      demoTitle: 'Comptes de demonstration',
      demoBody: 'Choisissez un role ci-dessous pour remplir le formulaire instantanement.',
      qrTitle: "Invitations QR generees par l'ecole",
      qrBody: "L'ecole peut generer une invitation QR securisee. Le scan ouvre un parcours parent guide.",
      join: "Ouvrir l'invitation QR",
      signInTitle: 'Connexion securisee par role',
      signInBody: 'Utilisez le bon code ecole, email et mot de passe pour entrer dans votre espace.',
      accessCodeBody: "Utilisez le code unique partage par l'ecole pour activer ou ouvrir votre compte.",
      biometricBody: 'La connexion biometrque est prete sur cet appareil de confiance.',
      loginHint: 'Chaque compte est redirige automatiquement vers le bon espace apres la connexion.',
      accessHint: "Les codes uniques simplifient la premiere activation ou l'acces parent.",
      qrHint: "Le scan d'une invitation QR lance directement un flux d'onboarding securise."
    },
    onboarding: {
      title: 'Bienvenue dans votre premiere session securisee',
      subtitle: "Un court parcours configure la langue, la visibilite et l'acces de confiance.",
      next: 'Suivant',
      back: 'Retour',
      finish: 'Terminer',
      skip: 'Passer',
      step: 'Etape',
      slides: [
        {
          title: "L'essentiel apparait en premier",
          body: 'Enfants, frais, mises a jour, reclamations et signaux operationnels sont visibles sans chercher partout.'
        },
        {
          title: 'Votre langue suit votre preference',
          body: 'Arabe, francais et anglais sont disponibles des la premiere connexion pour un confort immediat.'
        },
        {
          title: 'Les appareils de confiance accelerent le retour',
          body: 'Biometrie, inactivite protegee et visibilite des appareils gardent un acces rapide mais controle.'
        }
      ]
    },
    join: {
      title: 'Invitation scolaire securisee',
      subtitle: "Cette invitation QR a ete generee par l'ecole pour l'activation d'un compte parent.",
      linkedChildren: 'Enfants lies',
      linkedSchools: 'Ecoles liees',
      continue: "Continuer avec l'invitation",
      back: 'Retour a la connexion',
      invalid: 'Invitation introuvable. Demandez un nouveau QR code a l\'ecole.'
    },
    common: {
      signOut: 'Se deconnecter',
      support: 'Support',
      parentDashboard: 'Tableau parent',
      roleWorkspace: 'espace',
      currentDevice: 'Appareil actuel',
      lastActive: 'Derniere activite',
      trusted: 'De confiance',
      revoke: "Retirer l'appareil",
      devicesTitle: 'Appareils connectes',
      devicesBody: 'Consultez les sessions de confiance reliees a ce compte.',
      inactivityNote: "Deconnexion automatique apres 15 minutes d'inactivite",
      roleFoundation: 'Fondation du role',
      operationalSignals: 'Signaux operationnels',
      priorities: 'Priorites suivantes'
    }
  },
  ar: {
    auth: {
      chip: 'منصة مدرسية فاخرة',
      title: 'منصة آمنة واحدة، ستة أدوار، وتجربة مدرسية هادئة.',
      body: 'سجل الدخول بالحساب الذي قدمته المدرسة أو المنصة للدخول إلى المساحة المناسبة للآباء والإدارة والمعلمين والنقل والمراقبة وإدارة المنصة.',
      roleList: 'الأدوار المتاحة حاليا',
      codeTab: 'دخول المدرسة',
      accessCodeTab: 'رمز فريد',
      qrTab: 'الانضمام عبر QR',
      schoolCode: 'رمز المدرسة',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      accessCode: 'رمز ولي الأمر',
      continue: 'متابعة',
      biometric: 'الدخول بالبصمة',
      forgotPassword: 'نسيت كلمة المرور',
      recoveryTitle: 'استعادة الوصول عبر قناة آمنة',
      recoveryBody: 'أرسل رابط الاستعادة عبر القنوات الهاتفية الموثقة في الحساب.',
      sms: 'استعادة عبر SMS',
      whatsapp: 'استعادة عبر WhatsApp',
      language: 'اللغة',
      demoTitle: 'حسابات تجريبية',
      demoBody: 'اختر أي دور في الأسفل لملء النموذج مباشرة.',
      qrTitle: 'دعوات QR من المدرسة',
      qrBody: 'يمكن للمدرسة إنشاء دعوة QR آمنة، وعند مسحها يفتح مسار انضمام موجه لولي الأمر.',
      join: 'فتح دعوة QR',
      signInTitle: 'تسجيل دخول آمن حسب الدور',
      signInBody: 'استخدم رمز المدرسة الصحيح والبريد وكلمة المرور للدخول إلى مساحتك.',
      accessCodeBody: 'استخدم الرمز الفريد الذي شاركته المدرسة لتفعيل الحساب أو الدخول بسرعة.',
      biometricBody: 'الدخول البيومتري جاهز على هذا الجهاز الموثوق.',
      loginHint: 'يتم توجيه كل حساب تلقائيا إلى المساحة المناسبة بعد تسجيل الدخول.',
      accessHint: 'الرموز الفريدة تسهل أول تفعيل أو الدخول المبسط لولي الأمر.',
      qrHint: 'مسح دعوة QR ينقل ولي الأمر مباشرة إلى تدفق انضمام آمن.'
    },
    onboarding: {
      title: 'مرحبا بك في أول جلسة آمنة',
      subtitle: 'جولة سريعة تضبط اللغة والرؤية والوصول الموثوق للزيارات القادمة.',
      next: 'التالي',
      back: 'رجوع',
      finish: 'إنهاء الإعداد',
      skip: 'تخطي الآن',
      step: 'الخطوة',
      slides: [
        {
          title: 'المهم يظهر أولا',
          body: 'الأطفال والرسوم والتحديثات والشكايات والإشارات التشغيلية تظهر بدون الحاجة للتنقل بين قوائم كثيرة.'
        },
        {
          title: 'اللغة تتبع اختيارك',
          body: 'العربية والفرنسية والإنجليزية متاحة من أول تسجيل دخول حتى يشعر كل مستخدم بالراحة مباشرة.'
        },
        {
          title: 'الأجهزة الموثوقة تجعل العودة أسرع',
          body: 'الدخول البيومتري والحماية من الخمول ورؤية الأجهزة تحافظ على سرعة الوصول مع بقاء التحكم.'
        }
      ]
    },
    join: {
      title: 'دعوة مدرسية آمنة',
      subtitle: 'تم إنشاء دعوة QR هذه من طرف المدرسة لتفعيل حساب ولي الأمر.',
      linkedChildren: 'الأطفال المرتبطون',
      linkedSchools: 'المدارس المرتبطة',
      continue: 'متابعة بالدعوة',
      back: 'العودة لتسجيل الدخول',
      invalid: 'تعذر العثور على هذه الدعوة. اطلب رمز QR جديدا من المدرسة.'
    },
    common: {
      signOut: 'تسجيل الخروج',
      support: 'الدعم',
      parentDashboard: 'لوحة ولي الأمر',
      roleWorkspace: 'المساحة',
      currentDevice: 'الجهاز الحالي',
      lastActive: 'آخر نشاط',
      trusted: 'موثوق',
      revoke: 'إزالة الجهاز',
      devicesTitle: 'الأجهزة المسجلة',
      devicesBody: 'راجع الجلسات الموثوقة المرتبطة بهذا الحساب.',
      inactivityNote: 'تسجيل خروج تلقائي بعد 15 دقيقة من عدم النشاط',
      roleFoundation: 'أساس الدور',
      operationalSignals: 'الإشارات التشغيلية',
      priorities: 'الأولويات القادمة'
    }
  }
} as const

function getByPath(source: Record<string, unknown>, key: string) {
  return key.split('.').reduce<unknown>((value, segment) => (value as Record<string, unknown> | undefined)?.[segment], source)
}

export function getLanguage(storage: Storage | null = import.meta.client ? window.localStorage : null): SupportedLanguage {
  const stored = storage?.getItem(LANGUAGE_STORAGE_KEY)
  return SUPPORTED_LANGUAGES.some((item) => item.code === stored) ? (stored as SupportedLanguage) : 'en'
}

export function setLanguage(language: SupportedLanguage, storage: Storage | null = import.meta.client ? window.localStorage : null) {
  storage?.setItem(LANGUAGE_STORAGE_KEY, language)
}

export function getLanguageMeta(language: SupportedLanguage) {
  return SUPPORTED_LANGUAGES.find((item) => item.code === language) ?? SUPPORTED_LANGUAGES[0]
}

export function t(language: SupportedLanguage, key: string) {
  return getByPath(messages[language] as unknown as Record<string, unknown>, key) ?? getByPath(messages.en as unknown as Record<string, unknown>, key) ?? key
}
